# Generated by Django 3.1.1 on 2020-09-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=512)),
                ('num_triggers', models.IntegerField(default=0)),
            ],
        ),
    ]
