# Generated by Django 3.1.1 on 2020-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggers',
            name='num_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triggers',
            name='status',
            field=models.CharField(default='loading', max_length=16),
        ),
        migrations.AddField(
            model_name='triggers',
            name='video_title',
            field=models.CharField(default='', max_length=512),
        ),
    ]
