# Generated by Django 3.1.1 on 2020-09-25 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy', '0005_remove_triggers_dangerous_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggers',
            name='dangerous_frames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
    ]
