# Generated by Django 3.1.1 on 2020-09-26 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy', '0006_triggers_dangerous_frames'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('download_url', models.CharField(max_length=1024)),
                ('frames_to_remove', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None)),
                ('safe_video_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='triggers',
            name='frames_to_remove',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
