# Generated by Django 3.1.1 on 2020-09-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilepsy', '0007_auto_20200926_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='safevideo',
            name='status',
            field=models.CharField(default='loading', max_length=16),
        ),
    ]
